### ISSUE TITLE
Don't use --tmp-dir for vcf2maf

### ISSUE THREAD

**Issue by nikhil** [mskcc/roslin-variants#230]
vcf2maf needs to dynamically generate the temp dir to avoid collisions.

**Comment by ckandoth** [comment]
For provenance - by design, the `cmo_vcf2maf` wrapper forced CMO users to use `/scratch` instead of filling up `/tmp`. Since Roslin controls its own `TMPDIR`, we created and used a tool-level CWL for `vcf2maf.pl` script instead of the cmo-wrapper.
