### ISSUE TITLE
Run DMP-Val data sets in Prime

### ISSUE THREAD

**Issue by allanbolipata** [mskcc/roslin-variants#257]
Run DMP-Val files from 
```
/ifs/work/tangz/roslin_validation/dmpval_03_roslin241/run_roslin/01
```
on Prime.

Also look for DMP-Val 02.

**Comment by nikhil** [comment]
DMPval_03 batch 02 finished on PRIME

I used dmp val found in
```/ifs/work/tangz/roslin_validation/dmpval_03_roslin241/run_roslin/02/```

Results:
```/juno/work/pi/nikhil/roslin-pipelines/variant/2.5.0/outputs/Proj_DMPVal3_02.eb8502c8-92eb-11e9-9c90-ec0d9a88a1be```
Working directory:
```/juno/work/pi/nikhil/roslin-pipelines/variant/2.5.0/outputs/eb8502c8/eb8502c8-92eb-11e9-9c90-ec0d9a88a1be```
