### ISSUE TITLE
Minor updates for post-pipeline scripts

### ISSUE THREAD

**Issue by ckandoth** [mskcc/roslin-variants#272]
- [x] `maf_filter.py` - Tag mutations that will not be shown in portal. Use the `Mutation_Status` column in the analysis maf and tag events that are not shown in portal maf with `skipped_by_portal`.
- [x] `fusion_filter.py` - Ensure that merged post-filter SV MAF is created in `analysis` folder and delivered.

**Comment by Zuojian-Tang** [comment]
I removed the task below. We will generate `.bam.bai` file when we insert MSIsensor into roslin:
- `copy_outputs.json` - Ensure that `.bam.bai` files are retained for delivery, in addition to `.bai` files. The `.bam.bai` extension is needed for MSIsensor which uses an older htslib.
