### ISSUE TITLE
Commits from 2.4.x that 2.5.x must absorb

### ISSUE THREAD

**Issue by ckandoth** [mskcc/roslin-variants#273]
Make a list of the hotfixes in 2.4.1 and 2.4.2 made in production, as we found edge cases that our tests didn't cover. For example, https://github.com/mskcc/roslin-variant/commit/3ec29bf added 3 new assays for a priority project, but also changed the default curated BAM list to `AgilentExon_51MB_b37_v3` for assays that we did not prepare a curated BAM list for.

Ideally, this needs to be done before 2.5.0 is in production. But worst case, we will encounter similar issues in production, and need to make hotfixes post-release.

**Comment by ckandoth** [comment]
- [ ] Add support for 1 new IMPACT and 3 new WES assays (3ec29bf and ec73c7b)
- [ ] Default curated BAM list must be WES (3ec29bf)
- [ ] Quality/coverage thresholds for gatk_find_covered_intervals in module-2 (0018113)
- [ ] Disable `calculate_abra_ram_size()` in `roslin_request_to_yaml.py`. Always use 42GB in CWL and also in `java -Xmx` during execution. (2919689 and 4794db9)
- [ ] Bugfix for when sample names contain `R1` and  `R2` (f1d57f1 and 72353a7)
- [ ] Increase ramMin for some tools (425970c)
- [ ] Stop creating fillout MAFs since we don't do group fillout (7a2864f)
- [ ] Add cDNA contamination files to copy_outputs.json (45f7695)
- [ ] Make sure Toil cleans up after itself, and zip up logs (https://github.com/mskcc/roslin-core/commit/9d46841)
- [ ] (Optional) Ability to use human+mouse hybrid reference (4794db9)
- [ ] (Optional) Update package requirements for vulnerability issues (0e5e816)

**Comment by ckandoth** [comment]
@sivkovic @timosong @allanbolipata Removing these tasks since they were uniquely needed for 2.4.x only:
- Add option to specify `portal_repo_path` in analysis_helper and fix related bug (https://github.com/mskcc/roslin-core/commit/4ca7330, 133693c and fe64010)
- Add option to override `stable_id` in analysis_helper (fe64010 and https://github.com/mskcc/roslin-core/commit/6fa08c0)

**Comment by nikhil** [comment]
All sub-tickets closed, closing parent issue
