### ISSUE TITLE
Default curated BAM list must be WES

### ISSUE THREAD

**Issue by allanbolipata** [mskcc/roslin-variants#276]
As per #273, must change curated BAM list to default to WES.

See https://github.com/mskcc/roslin-variant/commit/3ec29bfdcbc444c6599e484640cf83a7c5d91aaa

**Comment by allanbolipata** [comment]
Just looking at the commit, it seems like this and #275 are duplicates, at least based on the commit hash provided. The changes are in PR https://github.com/mskcc/roslin-variant/pull/288

@ckandoth If it's the same, can we close this?

**Comment by ckandoth** [comment]
Yes, it looks like you have changed the default curated BAM list in PR #288.
