### ISSUE TITLE
Bugfix for when sample names contain R1 and R2

### ISSUE THREAD

**Issue by allanbolipata** [mskcc/roslin-variants#279]
See https://github.com/mskcc/roslin-variant/commit/f1d57f1774b959979ed590c89e11f05b2c639d7c and https://github.com/mskcc/roslin-variant/commit/72353a747f45ffe35863c3b6c70b28a676a97643

**Comment by nikhil** [comment]
cmo-split-reads for 2.5.x no longer depends on sample names
