### ISSUE TITLE
Facets image does not have fonts on axes labels

### ISSUE THREAD

**Issue by timosong** [mskcc/roslin-variants#335]
Could be that alpine is missing a font package? 
https://github.com/mskcc/roslin-variant/tree/2.6.x/build/containers/facets/1.6.2

Or the R script needs to adapt to the singularity image.  the doFacets script calls fplots_ggplot2.R, which I think is the one creating the image. 

https://github.com/mskcc/facets-suite/blob/master/fPlots_ggplot2.R

docker pull command:
https://hub.docker.com/r/mskcc/roslin-variant-facets

Example image:
/juno/res/ci/Proj_09455_M/dfd7102c-d66d-11e9-8f06-ec0d9a88a1c6/facets/s_C_6PL9CN_N001_d.rg.md.abra.printreads__s_C_6PL9CN_M001_d.rg.md.abra.printreads_purity.CNCF.png
![image](https://user-images.githubusercontent.com/700108/70731172-42591400-1cd4-11ea-9e33-0eb1b4cd70dc.png)

**Comment by stevekm** [comment]
Adding this to @nikhil  's [container](https://github.com/mskcc/roslin-variant/blob/1e4e0822e8f513f8f54f5de8e624224da5dc3a39/build/containers/facets/1.6.2/Dockerfile) seems to fix the problem:

```
apk --no-cache add msttcorefonts-installer && \
    update-ms-fonts && \
    fc-cache -f
```

![debug_output_2_ CNCF](https://user-images.githubusercontent.com/10505524/70744543-e1d7d000-1cef-11ea-945a-6b31fd6a1085.png)
